version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: Europe/Rome
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: updates
    versions:
    - 11.4.3
