version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 10
